name: orbita
description: "Plataforma Orbita (Clean Architecture + Riverpod)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# ===============================================
# DEPENDENCIAS DE LA APLICACIÓN
# ===============================================
dependencies:
  flutter:
    sdk: flutter

  # --- Core (Gestión de Estado y Navegación) ---
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0

  # --- Data (Networking y Almacenamiento) ---
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2

  # --- Biometría (Huella dactilar) ---
  local_auth: ^2.2.0

  # --- Modelos de Datos (Inmutabilidad y JSON) ---
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  image_picker: ^1.1.2   # Para acceder a la cámara y galería
  geolocator: ^12.0.0    # Para obtener la ubicación GPS

  # --- UI (íconos, etc) ---
  cupertino_icons: ^1.0.8

# ===============================================
# DEPENDENCIAS DE DESARROLLO (GENERACIÓN DE CÓDIGO)
# ===============================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # --- Generadores de código (Freezed, Riverpod, JSON) ---
  build_runner: ^2.4.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2

# ===============================================
# CONFIGURACIÓN DE FLUTTER
# ===============================================
flutter:
  uses-material-design: true

  # --- Assets (Imágenes, Iconos, Animaciones) ---
  # Asegúrate de crear esta carpeta en la raíz del proyecto
  assets:
    - assets/images/
    - assets/icons/
    # - assets/animations/

  # --- Fonts (Fuentes Personalizadas) ---
  # Asegúrate de crear esta carpeta y añadir los archivos .ttf
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #         style: italic